spring.application.name=ekart
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://sql.freedb.tech:3306/freedb_amx-db
spring.datasource.username=freedb_amxroot
spring.datasource.password=!F9Kb5z$zaZBSMU
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true
spring.jpa.database-platform=org.hibernate.dialect.MySQL5Dialect

#host sql.freedb.tech
#DB: freedb_amx-db
#User:freedb_amxroot
#Password:!F9Kb5z$zaZBSMU
